backend:
  name: github
  repo: 1JR4/wjr-portfolio
  branch: main

media_folder: "contents/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "contents/blogs"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Category", name: "category", widget: "select", options: ["AI & Engineering", "Technology & Innovation", "Product Management", "Finance & Technology", "Nature & Technology", "AI & Business"]}
      - {label: "Author", name: "author", widget: "string", default: "Wonjae Ra"}
      - {label: "Featured Image", name: "image", widget: "string", hint: "URL to header image"}
      - {label: "Tags", name: "tags", widget: "list", default: ["Technology"]}
      - {label: "TL;DR", name: "tldr", widget: "list", field: {label: "Point", name: "point", widget: "string"}}
      - {label: "Content", name: "content", widget: "markdown"}
      - label: "Table of Contents"
        name: "tableOfContents"
        widget: "list"
        required: false
        fields:
          - {label: "ID", name: "id", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Level", name: "level", widget: "number", default: 2, min: 1, max: 6}
      - label: "Resources"
        name: "resources"
        widget: "list"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["link", "pdf", "video"]}

  - name: "products"
    label: "Products"
    folder: "contents/products"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Full Description", name: "fullDescription", widget: "text", required: false}
      - {label: "Status", name: "status", widget: "select", options: ["live", "mvp", "development", "concept"]}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Icon URL", name: "icon", widget: "string", required: false, hint: "URL to product icon/logo"}
      - {label: "Type", name: "type", widget: "string", default: "web-app"}
      - {label: "Technologies", name: "technologies", widget: "list", default: ["React", "TypeScript"]}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "GitHub", name: "github", widget: "string", required: false}
      - {label: "Demo", name: "demo", widget: "string", required: false}
      - label: "KPIs"
        name: "kpis"
        widget: "list"
        required: false
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Value", name: "value", widget: "string"}
          - {label: "Trend", name: "trend", widget: "select", options: ["up", "down", "neutral"], required: false}