backend:
  name: git-gateway
  branch: main

media_folder: images
public_folder: /images

collections:
  - name: blog
    label: Blog Posts
    folder: blog
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
  
  - name: products
    label: Products
    folder: products
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Name, name: title, widget: string}
      - {label: Description, name: description, widget: text}
      - {label: Content, name: body, widget: markdown}